### ISSUE TITLE
Private key Recovery

### ISSUE THREAD

**Issue by Huntarh** [witee-star/BTCRecover-Advance#4]
Hello,
please I need your help recovering my uncompressed Bitcoin private key which has 10 characters missing. I was wondering if you could help me write a python or any other code that will bruteforce the 10 missing characters in a fast loop like the image below and check the balance of the private key.

![ezgif-3-dbd0978ecd](https://user-images.githubusercontent.com/107959503/176827875-3a51ccd1-2b4a-4594-8375-d8aa8e0de8e7.gif)

In the end if I find the correct private key I will give you some BTC.
let's talk on telegram

https://t.me/Huntarh
or email
ubongetimanthony@gmail.com

**Comment by witee-star** [comment]
Fixed
