### ISSUE TITLE
Traceback butball modules installed

### ISSUE THREAD

**Issue by Fatalityzocker** [witee-star/BTCRecover-Advance#8]
Hey, Install all with your Guide and with the Video. But when i start a Test the Bring me a traceback. I Put a Picture of it. I think anyone is needet. 
Python is 3.8.4rc1
![17078458627994114617873830904461](https://github.com/witee-star/BTCRecover-Advance/assets/159377361/386ec660-b1ba-4e78-9ac2-073eca31d591)
But eth Hash is installed.

Thx 😃

**Comment by TCRetriever** [comment]
Hey, download the updated version of btcrecover. Follow the link below:
https://github.com/witee-star/BTCRecover-master

**Comment by Fatalityzocker** [comment]
Ohh thank you so much. Try it over 2 hours but the new start instandly. Thank you, Hope i can rescue my wallet.

**Comment by TCRetriever** [comment]
If you still face any issue you can contact us on telegram : TCRetriever
